name: wordy
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.1
  http: ^0.12.2
  provider: ^4.3.2+2
  shared_preferences: ^0.5.12+4
  mockito: ^4.1.3
  async: ^2.4.2

  animated_text_kit: ^3.1.0
  path_provider: ^1.6.24
  flutter_svg: ^0.19.2+1
  flutter_spinkit: ^4.1.2
  throttling: ^0.9.0
  flutter_portal: ^0.3.0
  equatable: ^1.2.5
  showcaseview: ^0.1.6
  splashscreen:
  flutter_focus_watcher: ^0.0.1
  like_button: ^1.0.4
  focused_menu: ^1.0.2
  enum_to_string: ^1.0.14
  connectivity: ^2.0.2

dev_dependencies:
  test: ^1.15.7
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
   - assets/images/vocabulary.svg
   - assets/images/swipe-up.svg
   - assets/images/dictionary.png

  fonts:
   - family: Merriweather
     fonts:
       - asset: assets/fonts/Merriweather-Regular.ttf
       - asset: assets/fonts/Merriweather-Italic.ttf
         style: italic
       - asset: assets/fonts/Merriweather-Bold.ttf
         weight: 800
   - family: Lato
     fonts:
      - asset: assets/fonts/Lato-Regular.ttf
      - asset: assets/fonts/Lato-Bold.ttf
        weight: 800